steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--tag', 'gcr.io/aqueous-cargo-242610/go-grpc-hello:3.0', '.']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment.apps/grpc-hello', 'echo=gcr.io/aqueous-cargo-242610/go-grpc-hello:3.0']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'


  - name: 'gcr.io/cloud-builders/go'
    args: ['run', '/workspace/client/main.go', '--api-key=AIzaSyCd81cfAlsqpUxLS8NB89dKI25t54NGC9s', '--addr=34.77.182.157:80', 'Test successful!']
    env:
      - 'GOPATH=/workspace'
      - 'GO111MODULE=on'